### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by dereklucas** [printdotio/gooten-js#3]
Two questions that should probably be separate issues:
1) Which JS lib is recommended to work with, this one or https://github.com/printdotio/gooten-api-nodejs-client ?
2) With this lib, I'm running into CORS issues, is there anything I can do to fix that?

**Comment by micahasmith** [comment]
this one is only for client-side, and recommended over the gooten nodejs one.

first report we've had of CORS troubles-- all browsers?

**Comment by dereklucas** [comment]
Chrome:
```
Failed to load https://printio-geo.appspot.com/ip: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://testevent.arcivr.test' is therefore not allowed access.
```

Safari:
```
[Error] Origin http://testevent.arcivr.test is not allowed by Access-Control-Allow-Origin.
[Error] Failed to load resource: Origin http://testevent.arcivr.test is not allowed by Access-Control-Allow-Origin. (ip, line 0)
[Error] XMLHttpRequest cannot load https://printio-geo.appspot.com/ip due to access control checks.
```

(Edit: I got the browsers backwards. 🙄)

**Comment by dereklucas** [comment]
I guess an important note is this is the _just_ the user locator. The actual API `getProducts` call works great.

**Comment by micahasmith** [comment]
weird. I thought text/plain reqs, esp GETs, got around CORS.

this still works:

```
$.getJSON("https://printio-geo.appspot.com/ip/jsonp?callback=?",function(a,b){
  console.log(a,b)
})

```

aka, the jsonp

**Comment by dereklucas** [comment]
Update on this: I deployed the original code to a real domain name, and it works fine, so the problem is that I was calling from a `*.test` domain, not actually CORS settings.

**Comment by micahasmith** [comment]
!!! thank you for reporting that
